CREATE TABLE `invoiceItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` int NOT NULL,
	`productId` int,
	`code` varchar(50),
	`ean` varchar(14),
	`description` varchar(255) NOT NULL,
	`ncm` varchar(8) NOT NULL,
	`cest` varchar(7),
	`cfop` varchar(4) NOT NULL,
	`unit` varchar(10) NOT NULL DEFAULT 'UN',
	`quantity` int NOT NULL,
	`unitPrice` int NOT NULL,
	`totalPrice` int NOT NULL,
	`discount` int NOT NULL DEFAULT 0,
	`icmsOrigin` varchar(1) NOT NULL DEFAULT '0',
	`icmsCst` varchar(3) NOT NULL,
	`icmsBase` int NOT NULL DEFAULT 0,
	`icmsRate` int NOT NULL DEFAULT 0,
	`icmsValue` int NOT NULL DEFAULT 0,
	`ipiCst` varchar(2),
	`ipiBase` int NOT NULL DEFAULT 0,
	`ipiRate` int NOT NULL DEFAULT 0,
	`ipiValue` int NOT NULL DEFAULT 0,
	`pisCst` varchar(2) NOT NULL,
	`pisBase` int NOT NULL DEFAULT 0,
	`pisRate` int NOT NULL DEFAULT 0,
	`pisValue` int NOT NULL DEFAULT 0,
	`cofinsCst` varchar(2) NOT NULL,
	`cofinsBase` int NOT NULL DEFAULT 0,
	`cofinsRate` int NOT NULL DEFAULT 0,
	`cofinsValue` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `invoiceItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saleId` int,
	`number` int NOT NULL,
	`series` int NOT NULL DEFAULT 1,
	`model` varchar(2) NOT NULL DEFAULT '55',
	`type` enum('saida','entrada') NOT NULL DEFAULT 'saida',
	`status` enum('rascunho','emitida','cancelada','inutilizada','erro') NOT NULL DEFAULT 'rascunho',
	`emitterCnpj` varchar(18) NOT NULL,
	`emitterName` varchar(255) NOT NULL,
	`emitterFantasyName` varchar(255),
	`emitterAddress` text,
	`emitterCity` varchar(100),
	`emitterState` varchar(2),
	`emitterZipCode` varchar(10),
	`recipientDocument` varchar(18) NOT NULL,
	`recipientName` varchar(255) NOT NULL,
	`recipientAddress` text,
	`recipientCity` varchar(100),
	`recipientState` varchar(2),
	`recipientZipCode` varchar(10),
	`recipientPhone` varchar(20),
	`recipientEmail` varchar(255),
	`totalProducts` int NOT NULL DEFAULT 0,
	`totalDiscount` int NOT NULL DEFAULT 0,
	`totalFreight` int NOT NULL DEFAULT 0,
	`totalInsurance` int NOT NULL DEFAULT 0,
	`totalOtherExpenses` int NOT NULL DEFAULT 0,
	`totalIcms` int NOT NULL DEFAULT 0,
	`totalIpi` int NOT NULL DEFAULT 0,
	`totalPis` int NOT NULL DEFAULT 0,
	`totalCofins` int NOT NULL DEFAULT 0,
	`totalInvoice` int NOT NULL DEFAULT 0,
	`cfop` varchar(4) NOT NULL,
	`natureOperation` varchar(60) NOT NULL,
	`paymentMethod` enum('dinheiro','cheque','cartao_credito','cartao_debito','credito_loja','vale_alimentacao','vale_refeicao','vale_presente','vale_combustivel','boleto','deposito','pix','sem_pagamento','outros') NOT NULL,
	`paymentIndicator` enum('a_vista','a_prazo','outros') NOT NULL,
	`accessKey` varchar(44),
	`protocol` varchar(20),
	`authorizationDate` timestamp,
	`xmlUrl` text,
	`danfeUrl` text,
	`cancelReason` text,
	`canceledAt` timestamp,
	`cancelProtocol` varchar(20),
	`additionalInfo` text,
	`internalNotes` text,
	`issuedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`)
);
