CREATE TABLE `shipment_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shipment_id` int NOT NULL,
	`date` timestamp NOT NULL,
	`status` varchar(100) NOT NULL,
	`description` text NOT NULL,
	`location` varchar(255),
	`city` varchar(100),
	`state` varchar(2),
	`origin` varchar(255),
	`destination` varchar(255),
	`raw_data` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `shipment_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shipments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` int NOT NULL,
	`sale_id` int,
	`tracking_code` varchar(50) NOT NULL,
	`carrier` varchar(100) NOT NULL,
	`service` varchar(100),
	`status` enum('pending','posted','in_transit','out_delivery','delivered','failed','returned','cancelled') NOT NULL DEFAULT 'pending',
	`from_name` varchar(255) NOT NULL,
	`from_postal_code` varchar(9) NOT NULL,
	`from_address` text,
	`from_city` varchar(100),
	`from_state` varchar(2),
	`to_name` varchar(255) NOT NULL,
	`to_postal_code` varchar(9) NOT NULL,
	`to_address` text,
	`to_city` varchar(100),
	`to_state` varchar(2),
	`to_phone` varchar(20),
	`weight` int,
	`length` int,
	`width` int,
	`height` int,
	`shipping_cost` int NOT NULL,
	`insurance_value` int,
	`estimated_delivery` timestamp,
	`posted_at` timestamp,
	`delivered_at` timestamp,
	`melhor_envio_id` varchar(100),
	`external_id` varchar(100),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shipments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shipping_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` int NOT NULL,
	`user_id` int,
	`from_postal_code` varchar(9) NOT NULL,
	`to_postal_code` varchar(9) NOT NULL,
	`weight` int NOT NULL,
	`length` int NOT NULL,
	`width` int NOT NULL,
	`height` int NOT NULL,
	`carrier` varchar(100) NOT NULL,
	`service` varchar(100) NOT NULL,
	`price` int NOT NULL,
	`delivery_time` int,
	`insurance_value` int,
	`receipt` boolean DEFAULT false,
	`own_hand` boolean DEFAULT false,
	`source` enum('correios','melhor_envio','manual') NOT NULL,
	`used` boolean NOT NULL DEFAULT false,
	`shipment_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `shipping_quotes_id` PRIMARY KEY(`id`)
);
